[package]
name = "vecchio"
version = "0.1.0"
authors = ["bowser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5"
rand = "0.7.3"
